# Add files to database

project_id: w210-capstone-ta

instance:
    name: w210-therapeutic-accelerator
    region: us-central1

database:
    connection: w210-capstone-ta:us-central1:articles
    region: us-central1
    user: postgres
    password: V>4;MYzd&.n^B&2%
    name: article_attributes
    ip_private: True

semantic_scholar:
    # Get info about the latest release
<<<<<<< HEAD
    releases:
        latest: http://api.semanticscholar.org/datasets/v1/release/latest
        release: http://api.semanticscholar.org/datasets/v1/release
        papers: http://api.semanticscholar.org/datasets/v1/release/latest/dataset/papers
    papers: 
        attributes: http://api.semanticscholar.org/datasets/v1/release/latest/dataset/papers
        papers: http://api.semanticscholar.org/datasets/v1/release/latest/dataset/s2orc

paths: 
    root: /home/nick_lee_berkeley_edu/
    mount: mount-folder
    papers: mount-attributes
    wkdir: therapeutic_accelerator/db_work/
=======
    latest: http://api.semanticscholar.org/datasets/v1/release/latest
    release: http://api.semanticscholar.org/datasets/v1/release
    papers: http://api.semanticscholar.org/datasets/v1/release/latest/dataset/papers

paths: 
    root: /home/nick_lee_berkeley_edu/
    mount: "mount-folder"
>>>>>>> e782620a0cdc7fc07f0caea121b0a8fe68c3f44d
